name: pomodoro
description: "A simple app for focused work using the Pomodoro technique."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'  

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0 
  flutter_screenutil: ^5.9.3
  audioplayers: ^6.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:  
  uses-material-design: true
  
  assets: 
    - assets/
    - assets/google.png
    - assets/apple.png
    - assets/facebook.png
    - assets/x.png
    - assets/clock.png
    - assets/password_new.png
    - assets/light_time.png
    - assets/dark_time.png
    - assets/light_task.png
    - assets/dark_task.png
    - assets/light_calendar.png
    - assets/dark_calendar.png
    - assets/avatar.jpg
    - assets/home_page_assets/
    - assets/sounds/rainfall.mp3
    - assets/sounds/ocean_waves.mp3
    - assets/sounds/forest_wind.mp3
    - assets/sounds/crackling_fire.mp3
    - assets/sounds/mountain_stream.mp3
    - assets/sounds/night_crickets.mp3
    - assets/sounds/thunderstorm.mp3