name: pomodoro
description: "A simple app for focused work using the Pomodoro technique."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^7.0.0
  flutter_screenutil: ^5.9.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/



# flutter_native_splash:
#  color: "#FF4749"
#  image: assets/images/clock.png
#  android: true
#  ios: true
#  web: true
